### PR TITLE
Set enforce_min_max_values to True for datetime transformers

### LINKED ISSUE #1676: Set enforce_min_max_values to True for datetime transformers
### Problem Description

Sometime datetime values generated by SDV synthesizer are out of bounds.

### Expected behavior

Set the `enforce_min_max_values` parameters of the datetime transformers to `True` by default to ensure that the synthetic data is always in the same range as the real data

### PR DESCRIPTION
**Pull request by R-Palazzo**
CU-86ayq41bk
Resolve #1676

In this PR, RDT is upgraded to 1.9.0
I also noticed that following the logic of this PR, the DataProcessor could be cleaned a bit, mostly concerning the `Floatformatter`. I propose to get rid of the `_update_numerical_transformer` and try to do something similar to this PR, so update the transformer inside `_update_transformers_by_sdtypes`. 
Let me know you thought about it, if we want to do this change and if yes, inside this PR or in a separate issue :wink:

### CODE REVIEW

**Comment by sdv-team** [comment]
Task linked: [CU-86ayq41bk SDV - Set enforce_min_max_values to True for datetime transformers #1676](https://app.clickup.com/t/86ayq41bk)

**Review by amontanez24 — COMMENTED** [review]
Can we add an integration test that asserts the datetime values are in the range?

**Review by amontanez24 — APPROVED** [review]
I think this should work!

**Review by pvk-developer — APPROVED** [review]
LGTM! Good solution 😉

**Pull request merged**
