### PR TITLE
Cleanup `utils` module: Make internal functions private

### LINKED ISSUE #1793: Cleanup `utils` module: Make internal functions private
Currently the SDV library has a `utils` module that contains many helper functions. Initially, all the functions in this file were intended to be internal only. However, we may soon add functions that are meant for public use (see #1792). 

To better distinguish internal vs. externally-available functions, we should **prepend an underscore to all the internal helper functions** that are not meant for end-users.

### PR DESCRIPTION
**Pull request by R-Palazzo**
CU-86azc5bc2
Resolve #1793

@npatki is `load_data_from_csv` meant for end-users?

### CODE REVIEW

**Comment by sdv-team** [comment]
Task linked: [CU-86azc5bc2 SDV - Add a utility to drop unknown references (and enforce referential integrity) #1792](https://app.clickup.com/t/86azc5bc2)

**Review by amontanez24 — COMMENTED** [review]
This looks good! Alternatively, should we just move all these private functions to a `_utils.py` to not cause confusion between the functions there and the ones meant as public utility functions? @npatki

**Comment by npatki** [comment]
> This looks good! Alternatively, should we just move all these private functions to a `_utils.py` to not cause confusion between the functions there and the ones meant as public utility functions? @npatki

Yeah this makes sense to me!

**Review by npatki — COMMENTED** [review]
Hi @R-Palazzo, without going through every line of code here -- my recommendation is to check the API docs and see what is public today (you can search "utils" in the search bar)

You asked before if `load_data_from_csvs` is public -- I don't see it anywhere in the docs. I do see a `load_csvs` though.

**Review by pvk-developer — APPROVED** [review]
LGTM; 

We do not have any function on `SDV-Enterprise` that could be affected by this right ?

**Comment by R-Palazzo** [comment]
@pvk-developer, that's a good point, thanks.
The chained inequality feature uses some of the `utils` methods, but it will be a quick fix after the next sdv release.

**Review by amontanez24 — APPROVED** [review]
since the whole module is private now we could make the functions public again lol. But I leave that up to you

**Pull request merged**
